# -*- coding: utf-8 -*-
"""CV_Part_3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1On-__dDuJuVZZ9uXjyxW7Ai7BcdKAUgb
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

image1_path = r"/content/drive/MyDrive/CV_Programming_1/Part_3/SIFT1_img.jpg"
image2_path = r"/content/drive/MyDrive/CV_Programming_1/Part_3/SIFT2_img.jpg"

img1 = cv2.imread(image1_path)
img2 = cv2.imread(image2_path)

gray_img1 = cv2.cvtColor(img1, cv2.COLOR_BGR2GRAY)
gray_img2 = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)

sift = cv2.SIFT_create()

keypoints1, descriptors1 = sift.detectAndCompute(gray_img1, None)
keypoints2, descriptors2 = sift.detectAndCompute(gray_img2, None)

def find_nn_matches(desc1, desc2):
    matches = []
    for i, d1 in enumerate(desc1):
        distances = np.linalg.norm(desc2 - d1, axis=1)
        nn_index = np.argmin(distances)
        matches.append(cv2.DMatch(i, nn_index, distances[nn_index]))
    return matches

nn_matches = find_nn_matches(descriptors1, descriptors2)

nn_matches = sorted(nn_matches, key=lambda x: x.distance)

num_top_matches = int(0.1 * len(nn_matches))
top_matches = nn_matches[:num_top_matches]

def draw_matches_with_color(img1, keypoints1, img2, keypoints2, matches, color):
    # Create a new output image that concatenates the two images
    height1, width1, _ = img1.shape
    height2, width2, _ = img2.shape
    output_img = np.zeros((max(height1, height2), width1 + width2, 3), dtype=np.uint8)
    output_img[:height1, :width1] = img1
    output_img[:height2, width1:] = img2

    # Draw lines between matching keypoints
    for match in matches:
        # Get the matching keypoints
        pt1 = tuple(np.round(keypoints1[match.queryIdx].pt).astype(int))
        pt2 = tuple(np.round(keypoints2[match.trainIdx].pt).astype(int) + np.array([width1, 0]))

        # Draw the matching keypoints
        cv2.circle(output_img, pt1, 5, color, 1)
        cv2.circle(output_img, pt2, 5, color, 1)
        cv2.line(output_img, pt1, pt2, color, 1)

    return output_img

single_color = (0, 255, 0)  # Green color
img_top_matches = draw_matches_with_color(img1, keypoints1, img2, keypoints2, top_matches, single_color)

img1_kp = cv2.drawKeypoints(img1, keypoints1, None, flags=cv2.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS)
img2_kp = cv2.drawKeypoints(img2, keypoints2, None, flags=cv2.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS)

plt.figure(figsize=(16, 8))

plt.subplot(1, 3, 1)
plt.imshow(cv2.cvtColor(img1_kp, cv2.COLOR_BGR2RGB))
plt.title('SIFT Keypoints Image 1')
plt.axis('off')

plt.subplot(1, 3, 2)
plt.imshow(cv2.cvtColor(img2_kp, cv2.COLOR_BGR2RGB))
plt.title('SIFT Keypoints Image 2')
plt.axis('off')

plt.subplot(1, 3, 3)
plt.imshow(cv2.cvtColor(img_top_matches, cv2.COLOR_BGR2RGB))
plt.title('Top 10% Keypoint Matches')
plt.axis('off')

plt.tight_layout()
plt.show()