# -*- coding: utf-8 -*-
"""CV_Part_1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IxwCiMKoM4ZCwzcS-KR7DNUSWva3Sz0W
"""



import numpy as np
from PIL import Image
import math
import os

directory = r"/content/drive/MyDrive/CV_Programming_1/Part_1"
image_names = ["filter1_img.jpg", "filter2_img.jpg"]
inputpath = os.path.join(directory, "input")
outputpath = os.path.join(directory, "result")
os.makedirs(outputpath, exist_ok=True)
output_name_extension = ["3x3", "5x5", "DOGX", "DOGY", "Sobel"]
padding_sizes = [1, 2, 1, 1, 1]
padmode = 'constant'
grayscale_mode = 'L'
filter_count = 5

gaussian_3x3_derivative = 1 / 16
gaussian_3x3_arr = np.array([[1, 2, 1], [2, 4, 2], [1, 2, 1]])
gaussian_3x3_arr_mul = gaussian_3x3_arr * gaussian_3x3_derivative
gaussian_3x3_arr_mul_shape = gaussian_3x3_arr_mul.shape

def Gaussian_3x3_filter(padding1_image_arr, row, col):
    ans = np.sum(gaussian_3x3_arr_mul * padding1_image_arr[row: row + gaussian_3x3_arr_mul_shape[0], col: col + gaussian_3x3_arr_mul_shape[1]])
    return ans

gaussian_5x5_derivative = 1 / 273
gaussian_5x5_arr = np.array([[1, 4, 7, 4, 1], [4, 16, 26, 16, 4], [7, 26, 41, 26, 7], [4, 16, 26, 16, 4], [1, 4, 7, 4, 1]])
gaussian_5x5_arr_mul = gaussian_5x5_arr * gaussian_5x5_derivative
gaussian_5x5_arr_mul_shape = gaussian_5x5_arr_mul.shape

def Gaussian_5x5_filter(padding2_image_arr, row, col):
    ans = np.sum(gaussian_5x5_arr_mul * padding2_image_arr[row: row + gaussian_5x5_arr_mul_shape[0], col: col + gaussian_5x5_arr_mul_shape[1]])
    return ans

DOGx_arr = np.array([[1, 0, -1], [2, 0, -2], [1, 0, -1]])
DOGx_arr_mul = DOGx_arr

def DOGx_filter(padding1_image_arr, row, col):
    ans = np.sum(DOGx_arr_mul * padding1_image_arr[row: row + DOGx_arr_mul.shape[0], col: col + DOGx_arr_mul.shape[1]])
    return ans

DOGy_arr = np.array([[1, 2, 1], [0, 0, 0], [-1, -2, -1]])
DOGy_arr_mul = DOGy_arr

def DOGy_filter(padding1_image_arr, row, col):
    ans = np.sum(DOGy_arr_mul * padding1_image_arr[row: row + DOGy_arr_mul.shape[0], col: col + DOGy_arr_mul.shape[1]])
    return ans

def Sobel_filter(padding1_image_arr, row, col):
    dogx_value = DOGx_filter(padding1_image_arr, row, col)
    dogy_value = DOGy_filter(padding1_image_arr, row, col)
    ans = math.sqrt(dogx_value**2 + dogy_value**2)
    return ans

for image_name in image_names:
    image = Image.open(os.path.join(inputpath, image_name)).convert(grayscale_mode)
    image_arr = np.array(image)

    filters = []
    filter_inputs = []
    for i in range(filter_count):
        paded_img_arr = np.pad(image_arr, padding_sizes[i], mode=padmode)
        filter_inputs.append(paded_img_arr)
        filters.append(np.empty(image_arr.shape))

    for row in range(image_arr.shape[0]):
        for col in range(image_arr.shape[1]):
            filters[0][row][col] = Gaussian_3x3_filter(filter_inputs[0], row, col)
            filters[1][row][col] = Gaussian_5x5_filter(filter_inputs[1], row, col)
            filters[2][row][col] = DOGx_filter(filter_inputs[2], row, col)
            filters[3][row][col] = DOGy_filter(filter_inputs[3], row, col)
            filters[4][row][col] = Sobel_filter(filter_inputs[4], row, col)

    for i in range(filter_count):
        filtered_img = Image.fromarray(filters[i]).convert(grayscale_mode)
        filtered_img.show()
        filtered_img.save(os.path.join(outputpath, output_name_extension[i] + "_" + image_name))