# -*- coding: utf-8 -*-
"""CV_Programming_02

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14kwmtXX81OZfUkLhcNI3X8Z8FkPSLvsi
"""

import numpy as np
from PIL import Image
import cv2 as cv

directory = r"/content/drive/MyDrive/CV_Programming_2/Exercise - 2"
inputpath = directory + "/input/"
outputpath = directory + "/result/"

image_names = ["frame1_a.png", "frame1_b.png", "frame2_a.png", "frame2_b.png"]

paddingmode = 'constant'
padded_imagearray = []
gray_imagearray = []
image_arrays = []
for image_name in image_names:
    rgb_image = cv.imread(inputpath + image_name)
    gray_image = cv.cvtColor(rgb_image, cv.COLOR_BGR2GRAY)
    image_arrays.append(rgb_image)
    gray_imagearray.append(gray_image)
    padded_img_array = np.pad(gray_image, 1, mode=paddingmode)
    padded_imagearray.append(padded_img_array)

Video_array = [[0, 1], [2, 3]]

DOGx_arr_mul = np.array([[1, 0, -1], [2, 0, -2], [1, 0, -1]])

def DOGx_filter(padded_img_arr, R, C):
    return np.sum(DOGx_arr_mul * padded_img_arr[R: R + DOGx_arr_mul.shape[0], C: C + DOGx_arr_mul.shape[1]])

# Derivative of Gaussian Filter Y
DOGy_arr_mul = np.array([[1, 2, 1], [0, 0, 0], [-1, -2, -1]])

def DOGy_filter(padded_img_arr, R, C):
    return np.sum(DOGy_arr_mul * padded_img_arr[R: R + DOGy_arr_mul.shape[0], C: C + DOGy_arr_mul.shape[1]])

frame1_int_mul = np.array([[-1, -1, -1], [-1, -1, -1], [-1, -1, -1]])
frame2_int_mul = np.array([[1, 1, 1], [1, 1, 1], [1, 1, 1]])

def doi(frame1, frame2, R, C):
    return np.sum((frame1_int_mul * frame1[R: R + frame1_int_mul.shape[0], C: C + frame1_int_mul.shape[1]])) + np.sum((frame2_int_mul * frame2[R: R + frame2_int_mul.shape[0], C: C + frame2_int_mul.shape[1]]))

for video in Video_array:
    img1 = image_arrays[video[0]]
    img2 = image_arrays[video[1]]
    gray_img1 = gray_imagearray[video[0]]
    gray_img2 = gray_imagearray[video[1]]
    frame1 = padded_imagearray[video[0]]
    frame2 = padded_imagearray[video[1]]
    dogx = np.empty(gray_img1.shape)
    dogy = np.empty(gray_img1.shape)
    diff_of_intensity = np.empty(gray_img1.shape)

    for R in range(img1.shape[0]):
        for C in range(img1.shape[1]):
            dogx[R][C] = DOGx_filter(frame1, R, C)
            dogy[R][C] = DOGy_filter(frame1, R, C)
            diff_of_intensity[R][C] = doi(frame1, frame2, R, C)

    parameters = dict(maxCorners=2000,
                      qualityLevel=0.001,
                      minDistance=4,
                      blockSize=4)

    track = cv.goodFeaturesToTrack(gray_img1, mask=None, **parameters)
    trackers = np.int32(track)
    tracker = np.reshape(trackers, newshape=[-1, 2])

    hx = np.ones(dogx.shape)
    hy = np.ones(dogx.shape)
    status = np.zeros(tracker.shape[0])
    PQ = np.zeros((2, 2))
    PS = np.zeros((2, 1))
    mask = np.zeros_like(img1)
    newTracker = np.zeros_like(tracker)

    for a, i in enumerate(tracker):
        x, y = i
        PQ[0, 0] = np.sum((dogx[y - 1:y + 2, x - 1:x + 2]) ** 2)
        PQ[1, 1] = np.sum((dogy[y - 1:y + 2, x - 1:x + 2]) ** 2)
        PQ[0, 1] = np.sum(dogx[y - 1:y + 2, x - 1:x + 2] * dogy[y - 1:y + 2, x - 1:x + 2])
        PQ[1, 0] = PQ[0, 1]  # Symmetric matrix
        PQinv = np.linalg.pinv(PQ)

        PS[0, 0] = -np.sum(dogx[y - 1:y + 2, x - 1:x + 2] * diff_of_intensity[y - 1:y + 2, x - 1:x + 2])
        PS[1, 0] = -np.sum(dogy[y - 1:y + 2, x - 1:x + 2] * diff_of_intensity[y - 1:y + 2, x - 1:x + 2])
        prod = np.matmul(PQinv, PS)

        hx[y, x] = prod[0]
        hy[y, x] = prod[1]

        newTracker[a] = [np.int32(x + hx[y, x]), np.int32(y + hy[y, x])]
        if np.int32(x + hx[y, x]) == x and np.int32(y + hy[y, x]) == y:
            status[a] = 0
        else:
            status[a] = 1

    good_new = newTracker[status == 1]
    good_old = tracker[status == 1]

    # Draw the tracks and save images
    for ind, (new, old) in enumerate(zip(good_new, good_old)):
        q, w = new.ravel()
        a, s = old.ravel()
        mask = cv.line(mask, (q, w), (a, s), (0, 255, 0), 2)
        newframe = cv.circle(img2, (q, w), 1, (0, 255, 0), -1)

    image = cv.add(newframe, mask)
    cv.imwrite(outputpath + "optical_flow_generated_" + image_names[video[0]], image)

    # Save Vx and Vy images
    #filtered_img_x = Image.fromarray(hx.astype(np.uint8))
    #filtered_img_y = Image.fromarray(hy.astype(np.uint8))
    #filtered_img_x.save(outputpath + "Vx_" + image_names[video[0]])
    #filtered_img_y.save(outputpath + "Vy_" + image_names[video[0]])

    hx = np.empty(gray_img1.shape)
    hy = np.empty(gray_img1.shape)
    PQ = np.zeros((2, 2))
    PS = np.zeros((2, 1))

    for R in range(img1.shape[0]):
        for C in range(img1.shape[1]):
            PQ[0, 0] = np.sum((dogx[R: R + frame1_int_mul.shape[0], C: C + frame1_int_mul.shape[1]]) ** 2)
            PQ[0, 1] = np.sum((dogx[R: R + frame1_int_mul.shape[0], C: C + frame1_int_mul.shape[1]]) * (dogy[R: R + frame1_int_mul.shape[0], C: C + frame1_int_mul.shape[1]]))
            PQ[1, 0] = PQ[0, 1]  # Symmetric matrix
            PQ[1, 1] = np.sum((dogy[R: R + frame1_int_mul.shape[0], C: C + frame1_int_mul.shape[1]]) ** 2)
            PQinv = np.linalg.pinv(PQ)

            PS[0, 0] = -np.sum(dogx[R: R + frame1_int_mul.shape[0], C: C + frame1_int_mul.shape[1]] * diff_of_intensity[R: R + frame1_int_mul.shape[0], C: C + frame1_int_mul.shape[1]])
            PS[1, 0] = -np.sum(dogy[R: R + frame1_int_mul.shape[0], C: C + frame1_int_mul.shape[1]] * diff_of_intensity[R: R + frame1_int_mul.shape[0], C: C + frame1_int_mul.shape[1]])
            prod = np.matmul(PQinv, PS)

            hx[R][C] = prod[0]
            hy[R][C] = prod[1]
    # Convert Vx and Vy images to 8-bit format for saving
    vx_img = cv.normalize(hx, None, 0, 255, cv.NORM_MINMAX)
    vy_img = cv.normalize(hy, None, 0, 255, cv.NORM_MINMAX)

    # Convert to uint8 for saving
    vx_img = np.uint8(vx_img)
    vy_img = np.uint8(vy_img)

    # Save the Vx and Vy images
    Image.fromarray(vx_img).save(outputpath + "vx_" + image_names[video[0]])
    Image.fromarray(vy_img).save(outputpath + "vy_" + image_names[video[0]])
    sqrtofhxhy = np.sqrt((hx ** 2) + (hy ** 2))
    filtered_img = Image.fromarray(sqrtofhxhy.astype(np.uint8))
    filtered_img.save(outputpath + "filtered_optical_flow_" + image_names[video[0]])